Repository bonitasoft/bonita-labs-doc, pull requests merged in 2018-11, with the labels that each got.

#45 feat(index): update for 1.1.0
  md/index.md
Labels: Feedback integrated, Review needed :eyes:

#46 feat(taxonomy): rename
  md/monitoring.md
  md/taxonomy.md
Labels: Review done

#48 fix(release note): security is now in the product
  md/release_notes.md
Labels: Review needed :eyes:

#50 Update release note with last changes made to 1.1.10
  md/release_notes.md
Labels: Review done

#53 feat(install): refactor getting_started and installation_guide
  md/getting_started.md
  md/installation_guide.md
  md/prerequisites.md
Labels: Review done
