Repository bonitasoft/bonita-labs-doc, pull requests merged in 2019-08, with the labels that each got.

#78 docs(status order): update the response of the rest api bici-case-api
  md/rest_extensions.md
Labels: Review done

#79 doc(rest api): add new_bic-info rest api
  md/rest_extensions.md
Labels: Review done, Review needed :eyes:

#80 RN 1.2.2 maintenance
  md/release_notes.md
Labels: Review done, WIP :radioactive:
