Repository bonitasoft/bonita-labs-doc, pull requests merged in 2019-07, with the labels that each got.

#60 docs(operations management) content update, review
  md/monitoring.md
Labels: Review done

#63 doc(prerequisites): remove ref to 'evaluation' mode
  md/prerequisites.md
Labels: Review done

#59 docs(process-mining): spelling review
  md/process_mining.md
Labels: Feedback integrated, Review needed :eyes:

#65 docs(monitoring): minimum 100 cases
  md/monitoring.md
Labels: Review needed :eyes:

#64 docs(configuration) content update, review
  md/configure.md
Labels: Review needed :eyes:

#66 docs(polling): polling removed, configuration updated
  md/configure.md
  md/polling.md
  md/taxonomy.md
Labels: Review needed :eyes:

#68 doc(rest api extension): provide examples
  md/rest_extensions.md
Labels: Review needed :eyes:

#61 feat(install): review installation guide
  md/architecture.md
  md/images/bici_installation_installer_full.svg
  md/images/bici_installation_installer_no_elasticsearch.svg
  md/images/bonita_ici_stack.png
  md/images/ici_logo.png
  md/images/omar.png
  md/installation_guide.md
  md/prerequisites.md
Labels: Review done

#62 doc(getting started): remove duplicated info with the 'install guide'
  md/getting_started.md
Labels: Review done

#69 doc(Living Applications): add screenshots
  md/configure.md
  md/images/la/configuration_polling_status.png
  md/images/la/configuration_process_configuration.png
  md/images/la/monitoring_analytics_case_indicators.png
  md/images/la/monitoring_analytics_task_indicators.png
  md/images/la/monitoring_case_execution_details.png
  md/images/la/monitoring_home_on_time.png
  md/monitoring.md
Labels: Review done

#67 docs(installation): added troubleshooting
  md/installation_guide.md
Labels: Review done

#70 docs(glossary): review all pages to make them follow the BICI glossary
  md/architecture.md
  md/configure.md
  md/index.md
  md/installation_guide.md
  md/monitoring.md
  md/next_step.md
  md/polling.md
  md/prerequisites.md
  md/process_mining.md
  md/rest_extensions.md
  md/taxonomy.md
Labels: Feedback integrated, Review needed :eyes:

#71 doc(archi): review terms used in the architecture schema
  md/images/bici_architecture.png
Labels: Review done

#72 doc(la): reduce images size
  md/images/la/configuration_polling_status.png
  md/images/la/configuration_process_configuration.png
  md/images/la/monitoring_analytics_case_indicators.png
  md/images/la/monitoring_analytics_task_indicators.png
  md/images/la/monitoring_case_execution_details.png
  md/images/la/monitoring_home_on_time.png
Labels: Review done

#74 docs(rest api extensions): update the response examples
  md/rest_extensions.md
Labels: Review done

#75 docs(rest api extensions): update the response examples for 'predictedOnTime'
  md/rest_extensions.md
Labels: Review done

#76 docs(unknown case): update the monitoring page
  md/monitoring.md
Labels: Review done

#73 wip: start updating the release notes
  md/images/la/monitoring_case_execution_details.png
  md/images/la/monitoring_home_on_time.png
  md/monitoring.md
  md/release_notes.md
Labels: Review done

#77 docs(release notes): update the release notes for 1.2.1
  md/release_notes.md
Labels: Review done
