Repository bonitasoft/bonita-labs-doc, pull requests merged in 2019-11, with the labels that each got.

#105 doc(index): add 1.3.0 content
  md/index.md
Labels: Review done

#102 chore(release notes): create the release notes for the version 1.3.0
  md/release_notes.md
Labels: Feedback integrated, Review needed :eyes:

#109 feat(prerequisites): update for BICI 1.2
  md/prerequisites.md
Labels: Review done

#108 feat(prerequisites): update for BICI 1.3
  md/prerequisites.md
Labels: Review done

#114 chore(release notes): create the release notes for the version 1.3.0
  md/release_notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:

#115 docs(case details): update the screenshot
  md/images/la/monitoring_case_execution_details.png
Labels: Review needed :eyes:
